title: "Festa Nazionale 2023 di Rifondazione Comunista"
description: ""
url: "https://festa2023.rifondazione.info" # the base hostname & protocol for your site
locale: "it"


markdown: kramdown
future: true
destination: _site
sass:
    sass_dir: _sass
include: ['_pages']