title: "Festa 2023"
description: ""
url: "" # the base hostname & protocol for your site
locale: "it"


markdown: kramdown
future: true
destination: _site
sass:
    sass_dir: _sass
include: ['_pages']